### ISSUE TITLE
account 

### ISSUE THREAD

**Issue by olivero09** [Loopring/dexwebapp#164]
I registered yesterday with metamask in brave browser. Today after starting the browser again and click on connect wallet "metamask" the login screen from meta mask is does not appear. 
How do I login into my account? 

Thx., 
Oliver

**Comment by ebirbe** [comment]
@olivero09 I am having the same issue as you, but I think it's related of some maintenance being performed today in the platform. As you can see here.

https://twitter.com/loopringorg/status/1272895891704295441

> How do I login into my account?

I think the best is to wait after that system upgrade ends and then report if this issue is still present.

**Comment by olivero09** [comment]
Thx, that might be it. I will wait and see what happens. 
Thx, again for letting me know. Much appreciated.

**Comment by xiaowheat** [comment]
@olivero09 The system upgrade is completed. Please take a look. Thanks.

**Comment by olivero09** [comment]
Thank you, looks good and works perfectly fine! Thx,
