### ISSUE TITLE
Improper checking of token allowance.

### ISSUE THREAD

**Issue by TomAFrench** [Loopring/dexwebapp#9]
Currently there seems to be an assumption that all users will set the token allowance to the maximum value on their first deposit. I set the token allowance to a relatively small just to be safe (around 20DAI)

I've just tried to put a little bit more in which would take me over the amount I have allowed the DEX contract to take. I noticed before sending the transaction but it could have resulted a reverted transaction if I wasn't careful which would be a pain.

I'm guessing there's a check being made somewhere which just tests if the allowance is greater than 0. This should be amended to check it in relation to the user's deposit in progress.

EDIT: further to this, a small ui element to ease setting the token approvals later would be greatly appreciated. Seems like I have to go to Etherscan and approve from the ABI interface which is pretty crap.

**Comment by dong77** [comment]
This is a good suggestion, going forward, we can provide an option to set approval equal to the amount of deposit. but we cannot set it even 1 larger than the required amount, otherwise, another deposit will have to cancel the existing too small allowance (according to ERC20 standard)  and set a new allowance, thus there will be 3 transactions for the next deposit.

**Comment by dong77** [comment]
Can you share an Ethereum address to receive the reward? Thank you.

**Comment by TomAFrench** [comment]
sure, my address is tomfrench.eth. Thank you!
